# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS CloudFormation template that deploys an IAM Role that will be used by the ASA-iam-key-auto-rotation-and-notifier-solution.yaml CloudFormation template."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ASA IAM Role Configurations
        Parameters:
          - IAMRoleName
          - AccountExecutionRoleName
          - RotationExecutionRoleName
          - InfraestructureAccountIDDEV
          - InfraestructureAccountIDPRD
    ParameterLabels:
      IAMRoleName:
        default: Assumed IAM Role Name
      AccountExecutionRoleName:
        default: IAM Execution Role Name for Account Lambda
      RotationExecutionRoleName:
        default: IAM Execution Role Name for rotation Lambda
      InfraestructureAccountIDDEV:
        default: Infraestructure AWS Account ID DEV
      InfraestructureAccountIDPRD:
        default: Infraestructure AWS Account ID PRD
Parameters:
  IAMRoleName:
    Description: "Enter the name of IAM Role that the main ASA-iam-key-auto-rotation-and-notifier-solution.yaml CloudFormation template will assume."
    Type: String
    Default: "asa-iam-key-rotation-list-accounts-role"
  AccountExecutionRoleName:
    Description: "Enter the name of the Account Lambda Execution Role that will assume the role to list accounts."
    Type: String
    Default: "asa-iam-key-rotation-account-inventory-lambda-execution-role"
  RotationExecutionRoleName:
    Description: "Enter the name of the Rotation Lambda Execution Role that will assume the role to list accounts."
    Type: String
    Default: "asa-iam-key-rotation-lambda-execution-role"
  InfraestructureAccountIDDEV:
    Description: "Enter the Infraestructure/deployment AWS Account ID that will you will be deploying the ASA-iam-key-auto-rotation-and-notifier-solution.yaml CloudFormation template to."
    Type: String
    Default: ""
  InfraestructureAccountIDPRD:
    Description: "Enter the Infraestructure/deployment AWS Account ID that will you will be deploying the ASA-iam-key-auto-rotation-and-notifier-solution.yaml CloudFormation template to."
    Type: String
    Default: ""  

Resources:
  ##################################################################
  # ASA IAM Role that will be assumed by the ASA IAM Key Rotation 
  #  Function.
  ##################################################################
  ASAIAMAssumedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRoleName
      Description: !Sub "IAM Assume Role used by ${InfraestructureAccountIDDEV} and ${InfraestructureAccountIDPRD} ASA-Account-Inventory Lambda. This role is used to list accounts in the Organization."
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              - !Sub arn:${AWS::Partition}:iam::${InfraestructureAccountIDDEV}:role/${AccountExecutionRoleName}
              - !Sub arn:${AWS::Partition}:iam::${InfraestructureAccountIDDEV}:role/${RotationExecutionRoleName}
              - !Sub arn:${AWS::Partition}:iam::${InfraestructureAccountIDPRD}:role/${AccountExecutionRoleName}
              - !Sub arn:${AWS::Partition}:iam::${InfraestructureAccountIDPRD}:role/${RotationExecutionRoleName}
          Action: sts:AssumeRole
      Policies:
          - PolicyName: AllowListOrgAccounts
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - organizations:ListAccounts
                    - organizations:ListAccountsForParent
                    - organizations:ListChildren
                  Resource: "*"
          - PolicyName: AllowSecretsManagerAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - secretsmanager:PutResourcePolicy
                    - secretsmanager:PutSecretValue
                    - secretsmanager:DescribeSecret
                    - secretsmanager:CreateSecret
                    - secretsmanager:GetResourcePolicy
                    - secretsmanager:ReplicateSecretToRegions
                  Resource:
                    - !Sub "arn:${AWS::Partition}:secretsmanager:*:${AWS::AccountId}:secret:*"
      Path: /